### PR TITLE
 [ui] Correct keyboard action wording. Contributes to MER#1305

### PR DESCRIPTION
**Pull request by Mikaela**

### CODE REVIEW

**Comment by Mikaela** [comment]
Reopened #31 which couldn't be reopened,  because of rebase or force push.

Now I would be interested to hear the following:
* How am I expected to find committing rules without them being referenced in README or CONTRIBUTING or anywhere else that I would read at GitHub?
* How does this pull request fix issue that is already RESOLVED FIXED?
* If you use the mer issue tracker, why there is separate issue tracker here?
    * Why you don't simply disable this issue tracker at https://github.com/sailfishos/sailfish-utilities/admin/

**Comment by deztructor** [comment]
It'd be better to avoid to be annoyed: emotions are bad advisors ;)

Answers:
- Good idea about adding link to contribution reference
- It can't fix fixed issue but can contribute to some issue ("Contributes to")
- While it'd be disabled and Mer one could be used, for some people who just want to submit a bug report or proposal and have github account, it'll be not convenient.

**Comment by Mikaela** [comment]
> While it'd be disabled and Mer one could be used, for some people who just want to submit a bug report or proposal and have github account, it'll be not convenient.

> It can't fix fixed issue but can contribute to some issue ("Contributes to")

How about you tell me directly what I am supposed to put as commit/PR title/message?

It will be more convenient than people wondering rules that make no sense such as GitHub pull requests only closing MER issues when there is no issue at MER, but only at GitHub for example...

**Comment by Mikaela** [comment]
The MER issue tracker could also be linked so people would find it and you could allow GitHub login there. https://developer.github.com/v3/oauth/

**Comment by deztructor** [comment]
Taking into account this is just a single patch and you are not going to maintain any SFOS or Mer project, I could tell you what should be put. I didn't know it before, so just refered to some policy while considered you are SFOS contributor, so you was involved into mailing list etc. And I have a lot of work to spend time searching for bugs, rules etc. when reviewing, so I am trying to ask contributors to care about it.

So, I checked: there is no corresponding bug for this change, so I created new metabug for similar changes (https://bugs.merproject.org/show_bug.cgi?id=1305). And in this case wording for this bug could be e.g. ```[ui] Correct keyboard action wording. Contributes to MER#1305```

**Comment by Mikaela** [comment]
Done. I hope this is the last thing I am going to do with this simple pull request, this is the most difficult project where I have ever contributed.

**Pull request merged**
