### PR TITLE
[ui]Fix notification only show once.Fixes MER#1359

### PR DESCRIPTION
**Pull request by 0312birdzhang**
Fix notification only show once bug in 1.1.9.28

### CODE REVIEW

**Comment by deztructor** [comment]
* Please explain and provide url to the original issue

* Please read [info about contribution rules](https://github.com/sailfishos/sailfish-utilities/blob/master/CONTRIBUTING.org) and format request according to it

**Comment by matthewvogt** [comment]
LGTM - the close() clears the replacesId property of the notification instance, so that the subsequent publish() will create a new notification and display the preview.

**Comment by deztructor** [comment]
@0312birdzhang Thanks for submitting bug into the Mer bugzilla. The only thing left is to fix commit ff92a1de02430d98f2493a364d216703479dc625 message. You changed pull request title while you should change [the subject of the commit message](https://help.github.com/articles/changing-a-commit-message/) itself.

**Comment by 0312birdzhang** [comment]
Changed title to https://github.com/sailfishos/sailfish-utilities/pull/37

**Pull request closed without merging**
