### PR TITLE
[ui] Added possibility to restart keyboard

### PR DESCRIPTION
**Pull request by plsng**
Sometimes the keyboard can get stuck or clipboard stops working so this should be handy. First time doing this so maybe I've made some mistakes.

I'm not sure if it should be higher up in the list of utilities in case the stuck keyboard would overlap with the button that needs to be pressed to restart it, this probably needs some testing.

### CODE REVIEW

**Comment by deztructor** [comment]
Ok, now I am almost back to business :) Sorry, I have a flu and was sick enough to avoid to do anything. PR looks fine, so I'll test it now.

**Comment by anandrkris** [comment]
Hi - I have faced clipboard update issue on couple of occasions while running U10 but unfortunately restarting this service as suggested in TJC did not help in my case.
>>systemctl --user restart maliit-server.service
Am all for adding workarounds (especially if it saves reboots and increases uptime :smile_cat: ) but we should identify / address the root cause of the issue before adding workarounds. :wink: If the bug is not reproducable then definitely such workarounds are a big gain. 
Am not at all suggesting Jolla is not doing it, just putting forth the view user should use these services rarely. Thanks.

**Comment by deztructor** [comment]
@anandrkris Sailfish utilities are not workarounds but helpers for cases when one need to restart device otherwise (standard advice of any OS care ;-) ). There is probability of bugs in any service and subsystem. So, there should be ability (if it is possible) to reinitialize subsystems w/o restarting device.

**Comment by anandrkris** [comment]
@deztructor Hmm, my remark was around people simply suggesting restarting service as a panacea for the issues.
*(I really benefit from restart n/w service option but would love not to use it....You know, what I mean :smile: )*

**Comment by deztructor** [comment]
@anandrkris This is, of course, not a panacea, it just increases the probability to get issue to disappear if issue is discovered w/o restarting device. Though the main trend in utilities development should be the ability to submit useful bug reports (with logs etc.).

**Pull request merged**
